### ISSUE TITLE
Help alt-text

### ISSUE THREAD

**Issue by MikeJJohnson** [lparchaeology/ark2#24]
Help overlays for fields

**Comment by MikeJJohnson** [comment]
Just add them to the translation system keyed on the attribute/field name but with a role of 'tooltip', then I think there's a standard Aria type thingy for that?

**Comment by MikeJJohnson** [comment]
Do we have this text anywhere?

**Comment by jlayt** [comment]
A help field has been added to the render context and can be used to get a 'tooltip' or 'help' role translation. Suggest using Bootstrap js tooltips (http://getbootstrap.com/javascript/#tooltips) along with bootstrap form data-help attributes to display a ? after the field, and on mouse over or click pop-up the tooltip. Not keen on the help text under the field as per http://getbootstrap.com/css/#forms-help-text as it takes too much space. Tooltips are consistent with current validation tooltips.
