### ISSUE TITLE
Coin Schema

### ISSUE THREAD

**Issue by MikeJJohnson** [lparchaeology/ark2#43]
Coin finds need Mint/Moneyer fields added, and an extra secondary material option. Implement as a Modtype.

**Comment by jlayt** [comment]
Added Mint and Looped to data model. Frontend needs to hide/unhide on change of type.

**Comment by MikeJJohnson** [comment]
20ce6827b8cae0e5c900fc74d020b222b0a3e24b
frontend hides these
